#!/usr/bin/env python3
"""app/oauth-client-id.txt se res/values/oauth.xml banao.

OAuth client ID app ke dedicated Google account ke Cloud project me ek baar
banta hai (Android type). Placeholder ho to build toot-ta nahi, par login
"setup baaki hai" bolega.
"""
import os
import xml.sax.saxutils as sax

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TXT_PATH = os.path.join(BASE, "app", "oauth-client-id.txt")
PROJ_PATH = os.path.join(BASE, "app", "oauth-project-id.txt")
OUT_PATH = os.path.join(BASE, "app", "src", "main", "res", "values", "oauth.xml")

CLIENT_ID = "PLACEHOLDER_OAUTH_CLIENT_ID"
PROJECT_ID = "PLACEHOLDER_PROJECT_ID"
try:
    with open(TXT_PATH, encoding="utf-8") as f:
        v = f.read().strip()
        if v and "PLACEHOLDER" not in v:
            CLIENT_ID = v
except Exception as e:
    print(f"warning: oauth-client-id.txt padh nahi paya ({e})")
try:
    with open(PROJ_PATH, encoding="utf-8") as f:
        v = f.read().strip()
        if v and "PLACEHOLDER" not in v:
            PROJECT_ID = v
except Exception as e:
    print(f"warning: oauth-project-id.txt padh nahi paya ({e})")

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
xml = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    '<!-- AUTO-GENERATED by tools/gen_oauth_values.py — haath se mat badlo -->\n'
    '<resources>\n'
    f'    <string name="google_oauth_client_id" translatable="false">{sax.escape(CLIENT_ID)}</string>\n'
    f'    <string name="google_cloud_project" translatable="false">{sax.escape(PROJECT_ID)}</string>\n'
    '</resources>\n'
)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write(xml)
print(f"oauth.xml likha: client_id={'SET' if 'PLACEHOLDER' not in CLIENT_ID else 'placeholder'}, "
      f"project={'SET' if 'PLACEHOLDER' not in PROJECT_ID else 'placeholder'}")
