#!/usr/bin/env python3
"""app/update-url.txt se res/values/update.xml banao (in-app updater ke liye)."""
import os
import xml.sax.saxutils as sax

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TXT_PATH = os.path.join(BASE, "app", "update-url.txt")
OUT_PATH = os.path.join(BASE, "app", "src", "main", "res", "values", "update.xml")

URL = "PLACEHOLDER_UPDATE_URL"
# CI me UPDATE_URL env se aata hai (repo ka raw version.json link); local par file se.
env_url = os.environ.get("UPDATE_URL", "").strip()
if env_url and env_url.startswith("http"):
    URL = env_url
else:
    try:
        with open(TXT_PATH, encoding="utf-8") as f:
            v = f.read().strip()
            if v and "PLACEHOLDER" not in v:
                URL = v
    except Exception as e:
        print(f"warning: update-url.txt padh nahi paya ({e})")

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
xml = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    '<!-- AUTO-GENERATED by tools/gen_update_values.py — haath se mat badlo -->\n'
    '<resources>\n'
    f'    <string name="update_url" translatable="false">{sax.escape(URL)}</string>\n'
    '</resources>\n'
)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write(xml)
print(f"update.xml likha: url={'SET' if 'PLACEHOLDER' not in URL else 'placeholder (updater dormant)'}")
